apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/metallb-operator/v0.13.11
patches:
  # Talos PodSecurity patch
  - target:
      kind: Namespace
      name: metallb-system
    path: namespace-patch.yaml
