apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      namespace: argocd
    path: overlay/homelab/argocd
    repoURL: https://github.com/Nosmoht/gitops-k8s-homelab.git
    targetRevision: HEAD
