apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-bootstrapper
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: linstor-api-ca
spec:
  ca:
    secretName: linstor-api-ca
