apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: piraeus-datastore
generatorOptions:
  disableNameSuffixHash: true
resources:
  - tls.yaml
  - linstor-cluster.yaml
  - linstor-satellite-configuration.yaml
  - storage-classes.yaml
  - https://github.com/piraeusdatastore/piraeus-operator//config/extras/monitoring?ref=v2.5.1
