apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../../base/cert-manager/v1.14.4
  - cluster-issuer.yaml
  - pod-monitor.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: cert-manager
