apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
commonLabels:
  app.kubernetes.io/instance: cert-manager
resources:
  - ../../../base/cert-manager/v1.14.3
  - cluster-issuer.yaml
  - pod-monitor.yaml
patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: cert-manager
