apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager
resources:
  - ../../../base/cert-manager/v1.14.5
  - cluster-issuer.yaml
  - pod-monitor.yaml
patches:
  - target:
      kind: Deployment
      name: cert-manager
    patch: |
      - op: add
        path: /spec/template/spec/containers/0/args/-
        value: --feature-gates=ExperimentalGatewayAPISupport=true