apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb-operator
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      namespace: metallb-system
    path: overlay/homelab/metallb-system
    repoURL: https://github.com/Nosmoht/gitops-k8s-homelab.git
    targetRevision: HEAD
