apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
spec:
  destination:
    namespace: metrics-server
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      namespace: metrics-server
    path: overlay/homelab/metrics-server
    repoURL: https://github.com/Nosmoht/gitops-k8s-homelab.git
    targetRevision: HEAD
