apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: piraeus-operator
  namespace: argocd
spec:
  destination:
    namespace: piraeus-datastore
    server: https://kubernetes.default.svc
  project: default
  source:
    kustomize:
      namespace: piraeus-datastore
    path: overlay/homelab/piraeus-operator
    repoURL: https://github.com/Nosmoht/gitops-k8s-homelab.git
    targetRevision: HEAD
